### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by bseditor** [LIRIK-SPENCER/Bombsquad-Server#11]
Plz add the things as switches mentioned below:
1. add switch to enable/disable tags shown right above the head.
2. add switch to disable the glow of the spaz
3. add switch to disable the stats (if already exists ignore this)
4. add switch to disable the warn system.
5. add switch to disable tickets sys (if already exists ignore)

**Comment by LIRIK-SPENCER** [comment]
I will work for this now !
