### ISSUE TITLE
Black Screen in-game

### ISSUE THREAD

**Issue by bseditor** [LIRIK-SPENCER/Bombsquad-Server#12]
Attaching SS of terminal
![Capture1](https://user-images.githubusercontent.com/51753219/134418619-dc6a88dc-d7dd-4df3-9431-b1b0ed176bf8.JPG)

**Comment by LIRIK-SPENCER** [comment]
Yeaaa sorry for this but now i have moved on screen text from `Map` class to `GameActivity` class. It just got solved. Thanks for pointing out !
