### ISSUE TITLE
/help in chat doesn't work

### ISSUE THREAD

**Issue by bseditor** [LIRIK-SPENCER/Bombsquad-Server#4]
Do I need to specify somewhere my unique-id and then should I expect its working?

**Comment by LIRIK-SPENCER** [comment]
Nope, update to the latest version it will work

**Comment by LIRIK-SPENCER** [comment]
https://user-images.githubusercontent.com/74240325/133208745-ca58f158-d676-4005-b771-4e215e5625bf.mp4

**Comment by bseditor** [comment]
If I doesn't need to specify my id anywhere then I think anyone can use this cmd and get admin or owner?

**Comment by LIRIK-SPENCER** [comment]
Actually i said about first run, but you can add your id here : 
https://github.com/LIRIK-SPENCER/Bombsquad-Server/blob/main/dist/ba_root/mods/data/roles.json
Hope i convinced you !

**Comment by Hussain967722** [comment]
Rank system and chatfilter ownership everything not working. Plz help

**Comment by bseditor** [comment]
> Actually i said about first run, but you can add your id here :
> https://github.com/LIRIK-SPENCER/Bombsquad-Server/blob/main/dist/ba_root/mods/data/roles.json
> Hope i convinced you !

Well what if something I didn't like and wanted to remove it. How I will be able to do that as you have mentioned abt the code is using C-extension?

**Comment by Hussain967722** [comment]
Plz show the all launching chmods for terminal.. Because I did all same but not working, 
Sudo apt update
Sudo apt install git
Sudo apt install python3-pip I did it all.

**Comment by Hussain967722** [comment]
Hi bsediter without ownership then all rank and chatfilter all working for u?

**Comment by Hussain967722** [comment]
Bsediter R u using 20.4lts ?

**Comment by bseditor** [comment]
> Bsediter R u using 20.4lts ?

You must use 20.4 lts for using latest scripts :)

**Comment by LIRIK-SPENCER** [comment]
> > Actually i said about first run, but you can add your id here :
> > https://github.com/LIRIK-SPENCER/Bombsquad-Server/blob/main/dist/ba_root/mods/data/roles.json
> > Hope i convinced you !
> 
> Well what if something I didn't like and wanted to remove it. How I will be able to do that as you have mentioned abt the code is using C-extension?

I have made a config file for it go check it in data folder where roles file kept as i have sent link earlier

**Comment by LIRIK-SPENCER** [comment]
> Plz show the all launching chmods for terminal.. Because I did all same but not working,
> Sudo apt update
> Sudo apt install git
> Sudo apt install python3-pip I did it all.

Beo i have checked it now and it wasnt importing my mods so i have fixed now, clean install once and it will work

**Comment by bseditor** [comment]
Gonna test your scripts! will notify u abt bugs if any and if I satisfied u will earn a star!!

**Comment by LIRIK-SPENCER** [comment]
> Gonna test your scripts! will notify u abt bugs if any and if I satisfied u will earn a star!!

yeaa sure but make sure you download latest version

**Comment by Hussain967722** [comment]
Plz type the launch commands

**Comment by LIRIK-SPENCER** [comment]
> Plz type the launch commands

https://github.com/LIRIK-SPENCER/Bombsquad-Server#installation-and-starting-server

**Comment by Hussain967722** [comment]
Oh thanks u so much bro

**Comment by Hussain967722** [comment]
Can u add me in discord

**Comment by Hussain967722** [comment]
MR-PRIME#7558

**Comment by LIRIK-SPENCER** [comment]
> Can u add me in discord

Sorry but i donno why my id doesnt getting recognised but you can join my server (its not fancy but we just need a place to talk :) )
https://discord.gg/45TaxuSFKq

**Comment by Hussain967722** [comment]
Thank u
