### ISSUE TITLE
Error while hosting on Pterodactyl Game Server

### ISSUE THREAD

**Issue by DeathGOD7** [LIRIK-SPENCER/Bombsquad-Server#5]
Gives error in pterodactyl.

```
BombSquad server manager 1.3 starting up (debug mode)...
Interactive mode enabled; use the 'mgr' object to interact with the server.
Type 'help(mgr)' for more information.Valid server config file loaded.

Launching server subprocess...
-cfgdir: 1: home/container/dist/bombsquad_headless: not found
>>> Error running server subprocess: [Errno 32] Broken pipe
Stopping subprocess...
Subprocess stopped.
```

**Comment by LIRIK-SPENCER** [comment]
The error is not from my side beoo, thats internal bs error, which version of python you are on ?

**Comment by DeathGOD7** [comment]
Pyhton Version : 3.8 ( Also tried in python version 3.9 )

**Comment by LIRIK-SPENCER** [comment]
Can you check your firewall at once

**Comment by DeathGOD7** [comment]
Firewall is good...but since as I am using pterodactyl game server cause I host multiple servers... (also has access to terminal of system). 
```-cfgdir: 1: home/container/dist/bombsquad_headless: not found```
It says this...also some people suggested that I installed lib for python...so I tried both 3.8 and 3.9 from system terminal.

**Comment by DeathGOD7** [comment]
Also this when I don't add shebang in bombsquad_headless file
```
 /home/container/dist/bombsquad_headless: Exec format error
Error running server subprocess: [Errno 32] Broken pipe
```

And people suggested I add shebang in headless file.

**Comment by LIRIK-SPENCER** [comment]
> Firewall is good...but since as I am using pterodactyl game server cause I host multiple servers... (also has access to terminal of system).
> `-cfgdir: 1: home/container/dist/bombsquad_headless: not found`
> It says this...also some people suggested that I installed lib for python...so I tried both 3.8 and 3.9 from system terminal.

Default bombsquad binaries and my binaries are compiled against python3.8 so using 3.9 wont work. As of your error i might think the error is of pterodactyl (as i donno what is this !)

**Comment by DeathGOD7** [comment]
Pterodactyl is a game server.
Since the server files are python files (I used generic python egg aka server type in ptero.)

**Comment by LIRIK-SPENCER** [comment]
> Pterodactyl is a game server.
> Since the server files are python files (I used generic python egg aka server type in ptero.)

I will try and check it !

**Comment by DeathGOD7** [comment]
If you want I can make temp server for your testing.

**Comment by LIRIK-SPENCER** [comment]
> Death GOD 7#2255

yeaa sure
